Parsing_File_main.cpp File Reference
#include <iostream>
#include `FileHandler.h`
#include `ParseFilecontent.h`
Functions
int main ()
In the main function you will find calling functions, creating objects and variable deceleration.
Function Documentation
main()
int main ()
In the main function you will find calling functions, creating objects and variable deceleration.
< Variables to save the path of the file.
< key_word this variables to save the searching word.
< Vector of string to save the words from the txt file and use it for searching.
Definition at line 27 of file Parsing_File_main.cpp.
References Parse_File_content::call_exit_fun(), Parse_File_content::counting_words(), FileHandler::open_file(), Parse_File_content::read_file(), and Parse_File_content::search_after_word().