Parse_File_content Class Reference
This Class is response to: *Read the file and show it on the screan. *Create a vector to save the words with out punctuation and close the txt-file. *Shows the number of words in the file. *Searching after a specific word in the file.
#include <ParseFilecontent.h>
Public Member Functions
Parse_File_content (FileHandler w_f)
Parse_File_content ()
virtual ~Parse_File_content ()
void print_vector (std::vector< std::string > word_vec)
this function to print out the word vector on the user screen.
void read_file (bool fstatuse, std::vector< std::string > &word_vec)
void counting_words ()
void search_after_word (std::string key_word, std::vector< std::string > &word_vec)
void call_exit_fun ()
Private Attributes
FileHandler m_working_file
An object from FileHandler class to be able to use easly the function open_file which declare in the FileHandler class.
Detailed Description
This Class is response to: *Read the file and show it on the screan. *Create a vector to save the words with out punctuation and close the txt-file. *Shows the number of words in the file. *Searching after a specific word in the file.
ParseFilecontent.h
Author
Amer Chahda AC.
Date
2018-08-03< std::locale, std::isalpha
Definition at line 23 of file ParseFilecontent.h.
Constructor & Destructor Documentation
Parse_File_content() [1/2]
Parse_File_content::Parse_File_content (FileHandler w_f)
Definition at line 10 of file ParseFilecontent.cpp.
Parse_File_content() [2/2]
Parse_File_content::Parse_File_content ()
Definition at line 15 of file ParseFilecontent.cpp.
 Parse_File_content()
Parse_File_content::~Parse_File_content () [virtual]
Definition at line 19 of file ParseFilecontent.cpp.
Member Function Documentation
call_exit_fun()
void Parse_File_content::call_exit_fun ()
This function call the exit_fun which located in FileHandler class doing this through the object that we created from the FileHandlerclass as a private attribute in Parse_File_content this called composition
Definition at line 116 of file ParseFilecontent.cpp.
References FileHandler::exit_file(), and m_working_file.
Referenced by main().
counting_words()
void Parse_File_content::counting_words ()
This function to counting the words inside the text file using istream_iterator which ignore the white space and distance function std::distance(in, end)
it is a ready function to measure the distance between start address to the end address
Parameters
in in first address.
in end last sddress.
Returns
distance The distance between them.
Definition at line 87 of file ParseFilecontent.cpp.
References FileHandler::get_file_path(), and m_working_file.
Referenced by main().
print_vector()
void Parse_File_content::print_vector (std::vector< std::string > word_vec)
this function to print out the word vector on the user screen.
Parameters
in word_vec the vector where we save the word from the text file.
Definition at line 28 of file ParseFilecontent.cpp.
Referenced by read_file().
read_file()
void Parse_File_content::read_file (bool fstatuse, std::vector< std::string > & word_vec)
Read the text file with passing two parameters:
Parameters
in fstatuse it is a boolean parameter to be sure that is the file is open.
out word_vec this vector to save the words and only the words from the text file.
Definition at line 41 of file ParseFilecontent.cpp.
References FileHandler::get_file_path(), m_working_file, FileHandler::open_file(), and print_vector().
Referenced by main().
search_after_word()
void Parse_File_content::search_after_word (std::string key_word, std::vector< std::string > & word_vec)
This function looking after a word in the text file:
Parameters
in key_word user word.
in word_vec the vector of words we created from the text file.
before searching after the word it is good to be sure that all the letters in it are small.
Definition at line 101 of file ParseFilecontent.cpp.
Referenced by main().
Member Data Documentation
m_working_file
FileHandler Parse_File_content::m_working_file [private]
An object from FileHandler class to be able to use easly the function open_file which declare in the FileHandler class.
Definition at line 38 of file ParseFilecontent.h.
Referenced by call_exit_fun(), counting_words(), and read_file().
The documentation for this class was generated from the following files:
ParseFilecontent.h
ParseFilecontent.cpp