FileHandler Class Reference
This header file contain a declaration of FileHandler class which is response to open and close the txt-file.
#include <FileHandler.h>
Public Member Functions
FileHandler (std::string fpath)
This cpp file contain the implementation of FileHandler class which is response to open and close the txt-file.
FileHandler ()
virtual ~FileHandler ()
std::string get_file_path ()
bool open_file ()
This function will open the txt file.
void exit_file ()
Private Attributes
std::string file_path
variable to save the path of the file.
Detailed Description
This header file contain a declaration of FileHandler class which is response to open and close the txt-file.
FileHandler.h
Author
Amer Chahda AC.
Date
2018-08-03
Definition at line 17 of file FileHandler.h.
Constructor & Destructor Documentation
FileHandler() [1/2]
FileHandler::FileHandler (std::string filepath)
This cpp file contain the implementation of FileHandler class which is response to open and close the txt-file.
FileHandler.cpp
Created on: 3 aug. 2018 Author: ACH11739 FileHandler.cpp
Author
Amer Chahda AC.
Date
2018-08-03
Definition at line 16 of file FileHandler.cpp.
References file_path.
FileHandler() [2/2]
FileHandler::FileHandler ()
Definition at line 21 of file FileHandler.cpp.
 FileHandler()
FileHandler::~FileHandler () [virtual]
Definition at line 25 of file FileHandler.cpp.
Member Function Documentation
exit_file()
void FileHandler::exit_file ()
This function to close the file
Definition at line 58 of file FileHandler.cpp.
References get_file_path().
Referenced by Parse_File_content::call_exit_fun().
get_file_path()
std::string FileHandler::get_file_path ()
Definition at line 30 of file FileHandler.cpp.
References file_path.
Referenced by Parse_File_content::counting_words(), exit_file(), open_file(), and Parse_File_content::read_file().
open_file()
bool FileHandler::open_file ()
This function will open the txt file.
Returns
file_statuse a boolean value of the file status `True` if the file was successfully open or `False` if not
Definition at line 39 of file FileHandler.cpp.
References get_file_path().
Referenced by main(), and Parse_File_content::read_file().
Member Data Documentation
file_path
std::string FileHandler::file_path [private]
variable to save the path of the file.
Definition at line 30 of file FileHandler.h.
Referenced by FileHandler(), and get_file_path().
The documentation for this class was generated from the following files:
FileHandler.h
FileHandler.cpp